// AUTO-GENERATED by logos-cpp-generator -- do not edit
#include "plain_module_qt_glue.h"
#include <QJsonArray>
#include <QJsonObject>
#include <QVariant>
#include <QString>
#include "logos_types.h"
#include "logos_qt_arg_decode.h"
#include <exception>

QVariant PlainModuleProviderObject::callMethod(const QString& methodName, const QVariantList& args)
{
    try {
    if (methodName == "echo_text") {
        return QVariant::fromValue(echo_text(logos::qtArgFromVariant<QString>(args.at(0), "arg0")));
    }
    if (methodName == "echo_bytes") {
        return QVariant::fromValue(echo_bytes(logos::qtArgFromVariant<QByteArray>(args.at(0), "arg0")));
    }
    if (methodName == "echo_int") {
        return QVariant::fromValue(echo_int(logos::qtArgFromVariant<qlonglong>(args.at(0), "arg0")));
    }
    if (methodName == "echo_uint") {
        return QVariant::fromValue(echo_uint(logos::qtArgFromVariant<qulonglong>(args.at(0), "arg0")));
    }
    if (methodName == "echo_bool") {
        return QVariant::fromValue(echo_bool(logos::qtArgFromVariant<bool>(args.at(0), "arg0")));
    }
    if (methodName == "echo_float") {
        return QVariant::fromValue(echo_float(logos::qtArgFromVariant<double>(args.at(0), "arg0")));
    }
    if (methodName == "echo_strings") {
        return QVariant::fromValue(echo_strings(logos::qtArgFromVariant<QStringList>(args.at(0), "arg0")));
    }
    if (methodName == "echo_ints") {
        return QVariant::fromValue(echo_ints(logos::qtArgListOf<int64_t>(args.at(0), "arg0")));
    }
    if (methodName == "translate") {
        return QVariant::fromValue(translate(args.at(0), logos::qtArgFromVariant<double>(args.at(1), "arg1")));
    }
    if (methodName == "bounds") {
        return QVariant::fromValue(bounds(args.at(0)));
    }
    if (methodName == "attributes") {
        return QVariant::fromValue(attributes(logos::qtArgFromVariant<QVariantMap>(args.at(0), "arg0")));
    }
    if (methodName == "describe") {
        return QVariant::fromValue(describe(args.at(0)));
    }
    if (methodName == "fetch") {
        return QVariant::fromValue(fetch(logos::qtArgFromVariant<QString>(args.at(0), "arg0")));
    }
    if (methodName == "reset") {
        reset();
        return QVariant(true);
    }
    } catch (const logos::CodecError& e) {
        qWarning() << "PlainModuleProviderObject::callMethod:" << methodName << "rejected:" << e.what();
        return logos::dispatchFailedVariant(providerName(), QString::fromUtf8(e.what()));
    } catch (const std::exception& e) {
        qWarning() << "PlainModuleProviderObject::callMethod:" << methodName << "failed:" << e.what();
        return QVariant();
    }
    qWarning() << "PlainModuleProviderObject::callMethod: unknown method:" << methodName;
    return QVariant();
}

QJsonArray PlainModuleProviderObject::getMethods()
{
    QJsonArray methods;
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_text");
        obj["returnType"] = QStringLiteral("QString");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_text(QString)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("s")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_bytes");
        obj["returnType"] = QStringLiteral("QByteArray");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_bytes(QByteArray)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QByteArray")}, {"name", QStringLiteral("b")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_int");
        obj["returnType"] = QStringLiteral("qlonglong");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_int(qlonglong)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("qlonglong")}, {"name", QStringLiteral("n")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_uint");
        obj["returnType"] = QStringLiteral("qulonglong");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_uint(qulonglong)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("qulonglong")}, {"name", QStringLiteral("n")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_bool");
        obj["returnType"] = QStringLiteral("bool");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_bool(bool)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("bool")}, {"name", QStringLiteral("b")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_float");
        obj["returnType"] = QStringLiteral("double");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_float(double)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("double")}, {"name", QStringLiteral("f")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_strings");
        obj["returnType"] = QStringLiteral("QStringList");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_strings(QStringList)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QStringList")}, {"name", QStringLiteral("v")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("echo_ints");
        obj["returnType"] = QStringLiteral("QVariantList");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("echo_ints(QVariantList)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QVariantList")}, {"name", QStringLiteral("v")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("translate");
        obj["returnType"] = QStringLiteral("Point");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("translate(Point,double)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("Point")}, {"name", QStringLiteral("p")}});
        params.append(QJsonObject{{"type", QStringLiteral("double")}, {"name", QStringLiteral("dx")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("bounds");
        obj["returnType"] = QStringLiteral("Point");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("bounds(QList<Point>)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QList<Point>")}, {"name", QStringLiteral("points")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("attributes");
        obj["returnType"] = QStringLiteral("QVariantMap");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("attributes(QVariantMap)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QVariantMap")}, {"name", QStringLiteral("tags")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("describe");
        obj["returnType"] = QStringLiteral("QVariant");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("describe(Point)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("Point")}, {"name", QStringLiteral("p")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("fetch");
        obj["returnType"] = QStringLiteral("LogosResult");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("fetch(QString)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("id")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("method");
        obj["name"] = QStringLiteral("reset");
        obj["returnType"] = QStringLiteral("void");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("reset()");
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["type"] = QStringLiteral("event");
        obj["name"] = QStringLiteral("moved");
        obj["signature"] = QStringLiteral("moved(Point,Point)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("Point")}, {"name", QStringLiteral("from")}});
        params.append(QJsonObject{{"type", QStringLiteral("Point")}, {"name", QStringLiteral("to")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    return methods;
}
