// AUTO-GENERATED by logos-cpp-generator -- do not edit
#pragma once

#include <QObject>
#include <QString>
#include <QVariant>
#include <QStringList>
#include <QVariantList>
#include <QVariantMap>
#include <QByteArray>
#include <QJsonArray>
#include <string>
#include <vector>
#include <cstdint>
#include <functional>

#include "logos_provider_object.h"
#include "interface.h"
#include "logos_types.h"
#include "logos_api.h"
#include "logos_module_context.h"
#include "logos_sdk.h"
#include <memory>
#include <type_traits>

#include "fixture_impl.h"

namespace {
inline QStringList lidlToQStringList(const std::vector<std::string>& v) {
    QStringList result;
    result.reserve(static_cast<int>(v.size()));
    for (const auto& s : v)
        result.append(QString::fromStdString(s));
    return result;
}

inline std::vector<std::string> lidlToStdStringVector(const QStringList& list) {
    std::vector<std::string> result;
    result.reserve(static_cast<size_t>(list.size()));
    for (const auto& s : list)
        result.push_back(s.toStdString());
    return result;
}
} // anonymous namespace

#include <nlohmann/json.hpp>

namespace {
inline QVariant nlohmannToQVariant(const nlohmann::json& j) {
    if (j.is_null())    return QVariant();
    if (j.is_boolean()) return QVariant(j.get<bool>());
    if (j.is_number_integer()) return QVariant(static_cast<qlonglong>(j.get<int64_t>()));
    if (j.is_number_unsigned()) return QVariant(static_cast<qulonglong>(j.get<uint64_t>()));
    if (j.is_number_float()) return QVariant(j.get<double>());
    if (j.is_string()) return QVariant(QString::fromStdString(j.get<std::string>()));
    if (j.is_array()) {
        QVariantList list;
        list.reserve(static_cast<int>(j.size()));
        for (const auto& elem : j)
            list.append(nlohmannToQVariant(elem));
        return QVariant(list);
    }
    if (j.is_object()) {
        QVariantMap map;
        for (auto it = j.begin(); it != j.end(); ++it)
            map.insert(QString::fromStdString(it.key()), nlohmannToQVariant(it.value()));
        return QVariant(map);
    }
    return QVariant();
}

#include "logos_result.h"
inline LogosResult stdResultToQt(const StdLogosResult& r) {
    LogosResult qr;
    qr.success = r.success;
    qr.value = nlohmannToQVariant(r.value);
    qr.error = r.error.empty() ? QVariant() : QVariant(QString::fromStdString(r.error));
    return qr;
}
} // anonymous namespace

class PlainModuleProviderObject : public LogosProviderBase {
    LOGOS_PROVIDER(PlainModuleProviderObject, "plain_module", "1.0.0")

public:
    QString echo_text(const QString& s) {
        auto _result = m_impl.echo_text(s.toStdString());
        return QString::fromStdString(_result);
    }

    QByteArray echo_bytes(const QByteArray& b) {
        auto _result = m_impl.echo_bytes(std::vector<uint8_t>(b.begin(), b.end()));
        return QByteArray(reinterpret_cast<const char*>(_result.data()), static_cast<int>(_result.size()));
    }

    qlonglong echo_int(qlonglong n) {
        auto _result = m_impl.echo_int(static_cast<int64_t>(n));
        return static_cast<qlonglong>(_result);
    }

    qulonglong echo_uint(qulonglong n) {
        auto _result = m_impl.echo_uint(static_cast<uint64_t>(n));
        return static_cast<qulonglong>(_result);
    }

    bool echo_bool(bool b) {
        auto _result = m_impl.echo_bool(b);
        return _result;
    }

    double echo_float(double f) {
        auto _result = m_impl.echo_float(f);
        return _result;
    }

    QStringList echo_strings(const QStringList& v) {
        auto _result = m_impl.echo_strings(lidlToStdStringVector(v));
        return lidlToQStringList(_result);
    }

    QVariantList echo_ints(const QVariantList& v) {
        auto _result = m_impl.echo_ints(lidlToStdVector_int(v));
        return lidlToQVariantList_int(_result);
    }

    Point translate(Point p, double dx) {
        return m_impl.translate(p, dx);
    }

    Point bounds(QList<Point> points) {
        return m_impl.bounds(points);
    }

    QVariantMap attributes(const QVariantMap& tags) {
        return m_impl.attributes(tags);
    }

    QVariant describe(Point p) {
        return m_impl.describe(p);
    }

    LogosResult fetch(const QString& id) {
        auto _result = m_impl.fetch(id.toStdString());
        return stdResultToQt(_result);
    }

    void reset() {
        m_impl.reset();
    }

protected:
    void onInit(LogosAPI* api) override {
        if (!api) return;
        m_logosModules = std::make_unique<LogosModules>(api);
        _logos_codegen_::maybeSetLogosModules(m_impl, m_logosModules.get());
        _logos_codegen_::maybeSetEmitEvent(m_impl,
            [this](const std::string& name, void* args) {
                emitEvent(QString::fromStdString(name),
                          *static_cast<QVariantList*>(args));
            });
        _logos_codegen_::maybeSetContext(m_impl,
            api->property("modulePath").toString().toStdString(),
            api->property("instanceId").toString().toStdString(),
            api->property("instancePersistencePath").toString().toStdString());
    }

protected:
    void emitMoved(Point from, Point to) {
        emitEvent("moved", QVariantList{QVariant::fromValue(from), QVariant::fromValue(to)});
    }

private:
    std::unique_ptr<LogosModules> m_logosModules;
    FixtureImpl m_impl;
};

class PlainModulePlugin : public QObject, public PluginInterface, public LogosProviderPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID LogosProviderPlugin_iid FILE "metadata.json")
    Q_INTERFACES(PluginInterface LogosProviderPlugin)

public:
    QString name() const override { return QStringLiteral("plain_module"); }
    QString version() const override { return QStringLiteral("1.0.0"); }
    LogosProviderObject* createProviderObject() override {
        return new PlainModuleProviderObject();
    }
};
