// AUTO-GENERATED by logos-cpp-generator -- do not edit
//
// Bodies for `logos_events:` methods declared in fixture_impl.h.
// Each call marshals typed args into a QVariantList and routes
// them through LogosModuleContext::emitEventImpl_, which the
// generated provider wires to LogosProviderBase::emitEvent.
#include "fixture_impl.h"
#include <QString>
#include <QByteArray>
#include <QStringList>
#include <QVariant>
#include <QVariantList>
#include <cstdint>
#include <string>
#include <vector>

void FixtureImpl::moved(QVariant from, QVariant to) {
    QVariantList _args{QVariant::fromValue(from), QVariant::fromValue(to)};
    this->emitEventImpl_("moved", &_args);
}

