#include "lidl_gen_cdylib_glue.h"
#include "lidl_emit_common.h"

#include <QTextStream>

QString lidlMakeCdylibGlueHeader(const ModuleDecl& module)
{
    const QString className = lidlToPascalCase(module.name);
    QString c;
    QTextStream s(&c);

    s << "// AUTO-GENERATED by logos-cpp-generator --cdylib -- do not edit\n";
    s << "//\n";
    s << "// The UNIFORM Qt-plugin glue over the common module-impl C ABI\n";
    s << "// (logos_module_impl.h). Identical regardless of the module's source\n";
    s << "// language (C++ or Rust): it only knows the C symbols, which are\n";
    s << "// linked in from the module's cdylib. logos_host loads it unchanged.\n";
    s << "#pragma once\n\n";
    s << "#include \"interface.h\"\n";
    s << "#include \"logos_api.h\"\n";
    s << "#include \"logos_provider_object.h\"\n";
    s << "#include \"logos_json_convert.h\"\n";
    s << "#include \"logos_module_impl.h\"\n";
    s << "#include \"logos_types.h\"\n";
    s << "#include <QObject>\n";
    s << "#include <QJsonArray>\n";
    s << "#include <QJsonDocument>\n";
    s << "#include <QSet>\n";
    s << "#include <QString>\n";
    s << "#include <QVariant>\n";
    s << "#include <QVariantList>\n";
    s << "#include <nlohmann/json.hpp>\n\n";

    // LogosProviderBase (not the bare interface): its informModuleToken saves
    // into the HOST-stack TokenManager — what ModuleProxy validates INBOUND
    // calls against — exactly as C++ provider modules do. The glue then ALSO
    // forwards every token across the C ABI for the cdylib's own stack.
    s << "class " << className << "CdylibProvider : public LogosProviderBase {\n";
    s << "public:\n";
    s << "    QVariant callMethod(const QString& methodName, const QVariantList& args) override;\n";
    s << "    QJsonArray getMethods() override;\n";
    s << "    bool informModuleToken(const QString& moduleName, const QString& token) override;\n";
    s << "    void setEventListener(EventCallback callback) override;\n";
    s << "    QString providerName() const override { return QStringLiteral(\"" << module.name << "\"); }\n";
    s << "    QString providerVersion() const override { return QStringLiteral(\"" << (module.version.isEmpty() ? QStringLiteral("1.0.0") : module.version) << "\"); }\n";
    s << "protected:\n";
    s << "    void onInit(LogosAPI* api) override;\n";
    s << "private:\n";
    s << "    EventCallback m_eventCallback;\n";
    s << "    static void emitTrampoline(const char* eventName, const char* dataJson, void* userData);\n";
    s << "};\n\n";

    // The root plugin must also implement PluginInterface — logos_host's
    // module_initializer hard-requires it before any provider detection.
    s << "class " << className << "CdylibPlugin : public QObject, public PluginInterface, public LogosProviderPlugin {\n";
    s << "    Q_OBJECT\n";
    s << "    Q_PLUGIN_METADATA(IID LogosProviderPlugin_iid FILE \"metadata.json\")\n";
    s << "    Q_INTERFACES(PluginInterface LogosProviderPlugin)\n";
    s << "public:\n";
    s << "    QString name() const override { return QStringLiteral(\"" << module.name << "\"); }\n";
    s << "    QString version() const override { return QStringLiteral(\"" << (module.version.isEmpty() ? QStringLiteral("1.0.0") : module.version) << "\"); }\n";
    s << "    LogosProviderObject* createProviderObject() override {\n";
    s << "        return new " << className << "CdylibProvider();\n";
    s << "    }\n";
    s << "};\n";
    return c;
}

QString lidlMakeCdylibGlueSource(const ModuleDecl& module)
{
    const QString className = lidlToPascalCase(module.name);
    const QString provider = className + "CdylibProvider";

    // Which methods return StdLogosResult — the glue re-materializes the Qt
    // LogosResult QVariant callers expect on the wire.
    QStringList resultMethods;
    for (const MethodDecl& md : module.methods)
        if (md.resultReturn) resultMethods << md.name;

    QString c;
    QTextStream s(&c);
    s << "// AUTO-GENERATED by logos-cpp-generator --cdylib -- do not edit\n";
    s << "#include \"" << module.name << "_cdylib_glue.h\"\n\n";

    s << "QVariant " << provider << "::callMethod(const QString& methodName, const QVariantList& args)\n{\n";
    s << "    nlohmann::json jArgs = nlohmann::json::array();\n";
    s << "    for (const QVariant& a : args)\n";
    s << "        jArgs.push_back(logos::qvariantToNlohmann(a));\n";
    s << "    const std::string dumped = jArgs.dump();\n";
    s << "    char* result = logos_module_dispatch(methodName.toUtf8().constData(), dumped.c_str());\n";
    s << "    if (!result) return QVariant();\n";
    s << "    nlohmann::json jResult = nlohmann::json::parse(result, nullptr, false);\n";
    s << "    logos_module_string_free(result);\n";
    s << "    if (jResult.is_discarded()) return QVariant();\n";
    if (!resultMethods.isEmpty()) {
        s << "    // StdLogosResult-returning methods: re-materialize the Qt LogosResult\n";
        s << "    // QVariant the wire expects ({success, value, error} crossed the C ABI).\n";
        s << "    static const QSet<QString> kResultMethods = {";
        for (int i = 0; i < resultMethods.size(); ++i) {
            s << "QStringLiteral(\"" << resultMethods[i] << "\")";
            if (i + 1 < resultMethods.size()) s << ", ";
        }
        s << "};\n";
        s << "    if (kResultMethods.contains(methodName) && jResult.is_object()) {\n";
        s << "        LogosResult lr;\n";
        s << "        lr.success = jResult.value(\"success\", false);\n";
        s << "        lr.value = logos::nlohmannToQVariant(jResult.value(\"value\", nlohmann::json()));\n";
        s << "        lr.error = jResult.contains(\"error\") && jResult[\"error\"].is_string()\n";
        s << "            ? QVariant(QString::fromStdString(jResult[\"error\"].get<std::string>()))\n";
        s << "            : QVariant();\n";
        s << "        return QVariant::fromValue(lr);\n";
        s << "    }\n";
    }
    s << "    return logos::nlohmannToQVariant(jResult);\n";
    s << "}\n\n";

    s << "QJsonArray " << provider << "::getMethods()\n{\n";
    s << "    char* json = logos_module_get_methods();\n";
    s << "    if (!json) return QJsonArray();\n";
    s << "    QJsonDocument doc = QJsonDocument::fromJson(QByteArray(json));\n";
    s << "    logos_module_string_free(json);\n";
    s << "    return doc.isArray() ? doc.array() : QJsonArray();\n";
    s << "}\n\n";

    s << "bool " << provider << "::informModuleToken(const QString& moduleName, const QString& token)\n{\n";
    s << "    // Host-stack save first: ModuleProxy validates INBOUND calls against\n";
    s << "    // the host's TokenManager (LogosProviderBase saves there).\n";
    s << "    const bool hostOk = LogosProviderBase::informModuleToken(moduleName, token);\n";
    s << "    // Then forward across the C ABI: the cdylib's own protocol stack\n";
    s << "    // (a separate static copy) authenticates the module's OUTBOUND calls.\n";
    s << "    const bool implOk = logos_module_accept_token(moduleName.toUtf8().constData(),\n";
    s << "                                                  token.toUtf8().constData()) == 0;\n";
    s << "    return hostOk && implOk;\n";
    s << "}\n\n";

    s << "void " << provider << "::setEventListener(EventCallback callback)\n{\n";
    s << "    m_eventCallback = std::move(callback);\n";
    s << "    logos_module_set_emit_callback(&" << provider << "::emitTrampoline, this);\n";
    s << "}\n\n";

    s << "void " << provider << "::emitTrampoline(const char* eventName, const char* dataJson, void* userData)\n{\n";
    s << "    auto* self = static_cast<" << provider << "*>(userData);\n";
    s << "    if (!self || !self->m_eventCallback || !eventName) return;\n";
    s << "    nlohmann::json payload = dataJson\n";
    s << "        ? nlohmann::json::parse(dataJson, nullptr, false)\n";
    s << "        : nlohmann::json::array();\n";
    s << "    if (payload.is_discarded() || !payload.is_array()) payload = nlohmann::json::array();\n";
    s << "    self->m_eventCallback(QString::fromUtf8(eventName),\n";
    s << "                          logos::nlohmannArgsToQVariantList(payload));\n";
    s << "}\n\n";

    s << "void " << provider << "::onInit(LogosAPI* api)\n{\n";
    s << "    QObject* obj = api;\n";
    s << "    if (!obj) return;\n";
    s << "    // Token FIRST: the cdylib runs its own protocol stack (a separate\n";
    s << "    // static copy with its own TokenManager). Seed it with the\n";
    s << "    // host-issued auth token the initializer surfaces as a property\n";
    s << "    // (set before registerObject, so it is visible here), under the\n";
    s << "    // same keys the initializer uses (\"core\" / \"capability_module\")\n";
    s << "    // — this authenticates the module's OUTBOUND calls (incl. the\n";
    s << "    // capability requestModule flow). Seeding before the context\n";
    s << "    // forward means on_context_ready/onContextReady can already make\n";
    s << "    // authenticated calls whenever the impl's ready-latch fires.\n";
    s << "    const QString authToken = obj->property(\"authToken\").toString();\n";
    s << "    if (!authToken.isEmpty()) {\n";
    s << "        logos_module_accept_token(\"core\", authToken.toUtf8().constData());\n";
    s << "        logos_module_accept_token(\"capability_module\", authToken.toUtf8().constData());\n";
    s << "    }\n";
    s << "    // Context LAST — comes from the host's property stamping on the\n";
    s << "    // LogosAPI object, forwarded across the C ABI; the cdylib never\n";
    s << "    // sees Qt. (The impl fires its context-ready hook once BOTH the\n";
    s << "    // context and the emit callback have been delivered.)\n";
    s << "    logos_module_set_context(\n";
    s << "        obj->property(\"modulePath\").toString().toUtf8().constData(),\n";
    s << "        obj->property(\"instanceId\").toString().toUtf8().constData(),\n";
    s << "        obj->property(\"instancePersistencePath\").toString().toUtf8().constData());\n";
    s << "}\n";
    return c;
}
