// UI-backend glue generation (see lidl_gen_ui.h).
//
// The authoring split for type=ui_qml + interface=universal:
//
//   USER-WRITTEN   the .rep (the view contract — full QtRO power: SLOTs,
//                  PROPs, SIGNALs) and the *Backend.{h,cpp} class deriving
//                  the repc <RepClass>SimpleSource + LogosModuleContext
//                  (which supplies onContextReady() and the modules() typed
//                  accessors, exactly like a universal core module impl).
//
//   GENERATED      the *Interface.h (PluginInterface + IID) and the
//                  *Plugin.{h,cpp} (Q_PLUGIN_METADATA, name()/version(),
//                  ViewPluginBase, and the Q_INVOKABLE initLogos that
//                  constructs LogosModules, wires it + the context into the
//                  backend — firing onContextReady — and registers the
//                  backend as the QtRO source).
//
// Existing LogosAPI*-based UI plugins (interface: legacy) are untouched.

#include "lidl_gen_ui.h"

#include <QFile>
#include <QRegularExpression>
#include <QTextStream>

bool lidlUiParseRepClass(const QString& repPath, QString* repClass, QString* whyNot)
{
    QFile f(repPath);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text)) {
        if (whyNot) *whyNot = "cannot read .rep file: " + repPath;
        return false;
    }
    const QString text = QString::fromUtf8(f.readAll());
    // Same extraction logos_module(REP_FILE ...) performs: the first class
    // declaration names the QtRO types (SimpleSource/Replica/ViewPluginBase).
    QRegularExpressionMatch m =
        QRegularExpression(QStringLiteral("class[ \\t]+([A-Za-z_][A-Za-z0-9_]*)")).match(text);
    if (!m.hasMatch()) {
        if (whyNot) *whyNot = "no `class <Name>` declaration found in " + repPath;
        return false;
    }
    if (repClass) *repClass = m.captured(1);
    return true;
}

QString lidlMakeUiInterfaceHeader(const UiGlueSpec& spec)
{
    QString h;
    QTextStream s(&h);
    s << "// AUTO-GENERATED by logos-qt-generator --backend ui -- do not edit\n";
    s << "#pragma once\n\n";
    s << "#include \"interface.h\"\n\n";
    s << "class " << spec.pluginBase << "Interface : public PluginInterface\n{\npublic:\n";
    s << "    virtual ~" << spec.pluginBase << "Interface() = default;\n};\n\n";
    s << "#define " << spec.pluginBase << "Interface_iid \"org.logos." << spec.pluginBase << "Interface\"\n";
    s << "Q_DECLARE_INTERFACE(" << spec.pluginBase << "Interface, " << spec.pluginBase << "Interface_iid)\n";
    return h;
}

QString lidlMakeUiGlueHeader(const UiGlueSpec& spec)
{
    QString h;
    QTextStream s(&h);
    s << "// AUTO-GENERATED by logos-qt-generator --backend ui -- do not edit\n";
    s << "#pragma once\n\n";
    s << "#include <QObject>\n#include <QString>\n#include <memory>\n\n";
    s << "#include \"" << spec.backendHeader << "\"\n";
    s << "#include \"" << spec.moduleName << "_ui_interface.h\"\n";
    s << "#include \"LogosViewPluginBase.h\"\n\n";
    s << "class LogosAPI;\nstruct LogosModules;\n\n";
    s << "// Generated UI plugin around the user-written " << spec.backendClass << ".\n";
    s << "// Owns the backend, wires the LogosModules typed-deps aggregate + the\n";
    s << "// module context into it on initLogos (firing onContextReady — so\n";
    s << "// dependency subscriptions are live before the view's first call), and\n";
    s << "// registers it as the QtRO source for the QML replica.\n";
    s << "class " << spec.pluginBase << "Plugin : public QObject,\n";
    s << QString(" ").repeated(22 + spec.pluginBase.size()) << "public " << spec.pluginBase << "Interface,\n";
    s << QString(" ").repeated(22 + spec.pluginBase.size()) << "public " << spec.repClass << "ViewPluginBase\n{\n";
    s << "    Q_OBJECT\n";
    s << "    Q_PLUGIN_METADATA(IID " << spec.pluginBase << "Interface_iid FILE \"metadata.json\")\n";
    s << "    Q_INTERFACES(" << spec.pluginBase << "Interface LogosViewPlugin)\n\npublic:\n";
    s << "    // Ctor/dtor are out-of-line: this header is compiled by moc TUs\n";
    s << "    // where LogosModules may be incomplete.\n";
    s << "    explicit " << spec.pluginBase << "Plugin(QObject* parent = nullptr);\n";
    s << "    ~" << spec.pluginBase << "Plugin() override;\n\n";
    s << "    QString name() const override { return QStringLiteral(\"" << spec.moduleName << "\"); }\n";
    s << "    QString version() const override { return QStringLiteral(\"" << spec.moduleVersion << "\"); }\n\n";
    s << "    Q_INVOKABLE void initLogos(LogosAPI* api);\n\n";
    s << "private:\n";
    s << "    std::unique_ptr<" << spec.backendClass << "> m_backend;\n";
    s << "    std::unique_ptr<LogosModules> m_logosModules;\n";
    s << "};\n";
    return h;
}

QString lidlMakeUiGlueSource(const UiGlueSpec& spec)
{
    QString c;
    QTextStream s(&c);
    s << "// AUTO-GENERATED by logos-qt-generator --backend ui -- do not edit\n";
    s << "#include \"" << spec.moduleName << "_ui_glue.h\"\n\n";
    s << "#include \"logos_api.h\"\n";
    s << "#include \"logos_module_context.h\"\n";
    s << "#include \"logos_sdk.h\"\n\n";
    s << spec.pluginBase << "Plugin::" << spec.pluginBase << "Plugin(QObject* parent)\n";
    s << "    : QObject(parent)\n";
    s << "    , m_backend(std::make_unique<" << spec.backendClass << ">())\n";
    s << "{\n}\n\n";
    s << spec.pluginBase << "Plugin::~" << spec.pluginBase << "Plugin() = default;\n\n";
    s << "void " << spec.pluginBase << "Plugin::initLogos(LogosAPI* api)\n{\n";
    s << "    if (m_logosModules || !api) return;\n";
    s << "    // Same wiring order as the universal core glue: typed-deps aggregate\n";
    s << "    // first, context LAST (maybeSetContext fires onContextReady — by then\n";
    s << "    // modules() is live, so the backend can make typed calls and\n";
    s << "    // subscribe to dependency events from the hook). The SFINAE helpers\n";
    s << "    // no-op if the backend doesn't derive LogosModuleContext.\n";
    s << "    m_logosModules = std::make_unique<LogosModules>(api);\n";
    s << "    _logos_codegen_::maybeSetLogosModules(*m_backend, m_logosModules.get());\n";
    s << "    QObject* obj = api;\n";
    s << "    _logos_codegen_::maybeSetContext(*m_backend,\n";
    s << "        obj->property(\"modulePath\").toString().toStdString(),\n";
    s << "        obj->property(\"instanceId\").toString().toStdString(),\n";
    s << "        obj->property(\"instancePersistencePath\").toString().toStdString());\n";
    s << "    // Register the backend (a " << spec.repClass << "SimpleSource) as the QtRO\n";
    s << "    // source so ui-host can enableRemoting the typed " << spec.repClass << "SourceAPI.\n";
    s << "    setBackend(m_backend.get());\n";
    s << "}\n";
    return c;
}
